services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - ./src/test/resources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql