services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - ./src/test/resources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    application:
        build:
            context: .
        environment:
            DB_URL: jdbc:postgresql://postgres:5432/postgres?prepareThreshold=0
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        ports:
            - 8080:8080
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL","curl --fail --silent localhost:8080/actuator/health/liveness | grep UP || exit 1" ]
            interval: 1s
            timeout: 5s
            retries: 3
            start_period: 5s
        profiles:
            -   application