spring:
    application:
        name: catalog-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?prepareThreshold=0}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 1
            leak-detection-threshold: 30000
            connection-timeout: 5000

server:
    shutdown: "graceful"

springdoc:
    swagger-ui:
        layout: BaseLayout